version: 0.2

env:
  shell: bash
  git-credential-helper: no

phases:
  build:
    commands:
      - TAG=$(echo $CODEBUILD_WEBHOOK_TRIGGER | cut -c5- )      
      - ${CODEBUILD_SRC_DIR}/docker/coturn/build_docker.sh ${CODEBUILD_SRC_DIR} ${CODEBUILD_WEBHOOK_TRIGGER}
